*** Reading local file: /opt/airflow/logs/func/get_data/2022-02-25T20:59:49.556540+00:00/1.log
[2022-02-25, 20:59:52 UTC] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: func.get_data manual__2022-02-25T20:59:49.556540+00:00 [queued]>
[2022-02-25, 20:59:52 UTC] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: func.get_data manual__2022-02-25T20:59:49.556540+00:00 [queued]>
[2022-02-25, 20:59:52 UTC] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-02-25, 20:59:52 UTC] {taskinstance.py:1239} INFO - Starting attempt 1 of 3
[2022-02-25, 20:59:52 UTC] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-02-25, 20:59:52 UTC] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): get_data> on 2022-02-25 20:59:49.556540+00:00
[2022-02-25, 20:59:52 UTC] {standard_task_runner.py:52} INFO - Started process 7164 to run task
[2022-02-25, 20:59:52 UTC] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'func', 'get_data', 'manual__2022-02-25T20:59:49.556540+00:00', '--job-id', '100', '--raw', '--subdir', 'DAGS_FOLDER/test_task_dag.py', '--cfg-path', '/tmp/tmp_pfn79pg', '--error-file', '/tmp/tmph7rr730l']
[2022-02-25, 20:59:52 UTC] {standard_task_runner.py:77} INFO - Job 100: Subtask get_data
[2022-02-25, 20:59:52 UTC] {logging_mixin.py:109} INFO - Running <TaskInstance: func.get_data manual__2022-02-25T20:59:49.556540+00:00 [running]> on host a8a367e07e36
[2022-02-25, 20:59:52 UTC] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=func
AIRFLOW_CTX_TASK_ID=get_data
AIRFLOW_CTX_EXECUTION_DATE=2022-02-25T20:59:49.556540+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-02-25T20:59:49.556540+00:00
[2022-02-25, 20:59:52 UTC] {python.py:175} INFO - Done. Returned value was: None
[2022-02-25, 20:59:52 UTC] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=func, task_id=get_data, execution_date=20220225T205949, start_date=20220225T205952, end_date=20220225T205952
[2022-02-25, 20:59:52 UTC] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-02-25, 20:59:53 UTC] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check


